name: herokuDeploy

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    
#set environment variables 
env:
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy_if_merged:
    name: Deploy to Heroku
    
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:

    # Checkout repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push worker -a $HEROKU_APP_NAME
        heroku container:release worker -a $HEROKU_APP_NAME
